module.exports = {
	IOT_API_KEY:'<IOT_API_KEY>',
	IOT_AUTH_TOKEN:'<IOT_AUTH_TOKEN>',
	IOT_ORG:'<IOT_ORG>',
	IOT_DEVICE_TYPE:'<IOT_DEVICE_TYPE>',
	IOT_DEVICE_ID:'<IOT_DEVICE_ID>',
	TEXT_TO_SPEECH_USERNAME:'<TEXT_TO_SPEECH_USERNAME>',
	TEXT_TO_SPEECH_PASSWORD:'<TEXT_TO_SPEECH_PASSWORD>'
}
