version : 0.0.2
container-name-run : "remoterobot-swift-run"
container-name-tools : "remoterobot-swift-tools"
image-name-run : "remoterobot-swiftrun"
image-name-tools: "remoterobot-swifttools"
dockerfile-tools: "Dockerfile-tools"
dockerfile-run: "Dockerfile"
build-cmd-debug : "/root/utils/tools-utils.sh build debug"
debug-cmd : "/root/utils/tools-utils.sh debug Remote-Robot 1024"
build-cmd-run : "/root/utils/tools-utils.sh build release"
run-cmd : "/root/utils/run-utils.sh run Remote-Robot"
test-cmd : "/root/utils/tools-utils.sh test"
container-path-run : "/root/project"
container-path-tools : "/root/project"
container-port-map : "8080:8080"
container-port-map-debug : "2048:1024,2049:1025"
